export const CONTACT_LIST_REQUEST = 'CONTACT_LIST_REQUEST';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CONTACT_LIST_FAIL = 'CONTACT_LIST_FAIL';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SUBMIT_UPDATED_CONTACT = 'SUBMIT_UPDATED_CONTACT';
export const SET_SORT_PROP = 'SET_SORT_PROP';
